# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e0789506fdd7eb032e3622068f3b7e96f5e3b05f18d786665513c3e51410e266f76d35394bad2ac4701ff252bd9be672a5f2aa4a6080544e0d5707016ba805e

test:
  secret_key_base: 7a727378274af1228e15d8576b6ada9a23309c02f99f9692c39f2d020b81cad12ce5a34daddb30166daa77738f2742a2f60663d874aabb1c07d56f84457e0d1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
